# La descomposición polar

In [1]:
import numpy as np
from scipy.linalg import polar, eigh, inv, det, svd, eigvalsh

Primero que todo se genera al azar una matriz $\boldsymbol{F}$:

In [2]:
F = np.random.rand(3,3)
F

array([[0.63507913, 0.03279025, 0.01333886],
       [0.8291054 , 0.52737216, 0.37148524],
       [0.88525969, 0.17426902, 0.52598688]])

La descomposición polar la matriz $\boldsymbol{F}$ se puede descomponer así:

\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{V}\boldsymbol{R}
\end{equation*}

donde $\boldsymbol{R}$ es una matriz ortogonal y $\boldsymbol{U}$ y $\boldsymbol{V}$ son matrices simétricas.

La función `scipy.linalg.polar` se puede utilizar para generar la descomposición polar:

In [3]:
R1, U = polar(F, 'right')
R2, V = polar(F, 'left')

Observe que las matrices $\boldsymbol{R}_1$ y $\boldsymbol{R}_2$ son iguales:

In [4]:
R1 - R2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Por lo tanto:

In [5]:
R = R1

Observemos también que $\boldsymbol{R}$ es una matriz ortogonal, es decir, satisface $\boldsymbol{R}^T\boldsymbol{R} = \boldsymbol{I}$:
    

In [6]:
R.T @ R

array([[1.00000000e+00, 2.16719574e-16, 3.42138681e-16],
       [2.16719574e-16, 1.00000000e+00, 2.05181966e-16],
       [3.42138681e-16, 2.05181966e-16, 1.00000000e+00]])

y que $\boldsymbol{R}$ es una *matriz ortogonal propia*, es decir, su determinante $\det(\boldsymbol{R}) = \pm 1$:

In [7]:
det(R)

1.0000000000000009

Tanto la matriz $\boldsymbol{U}$ como la matriz $\boldsymbol{V}$ son simétricas:

In [8]:
U

array([[1.26200142, 0.32002599, 0.42351123],
       [0.32002599, 0.42029346, 0.17465124],
       [0.42351123, 0.17465124, 0.4527434 ]])

In [9]:
V

array([[0.47035065, 0.27949603, 0.32439305],
       [0.27949603, 0.84433845, 0.55902861],
       [0.32439305, 0.55902861, 0.82034918]])

y también son definidas positivas, ya que todos sus valores propios son positivos:

In [10]:
eigvalsh(U)

array([0.25107085, 0.32508402, 1.55888341])

In [11]:
eigvalsh(V)

array([0.25107085, 0.32508402, 1.55888341])

Verifiquemos ahora que:
\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{V}\boldsymbol{R}
\end{equation*}

In [12]:
F - R@U

array([[-6.66133815e-16, -2.22044605e-16, -4.68375339e-16],
       [-1.33226763e-15, -4.44089210e-16, -6.66133815e-16],
       [-1.44328993e-15, -4.44089210e-16, -5.55111512e-16]])

In [13]:
F - V@R

array([[-6.66133815e-16, -2.35922393e-16, -3.71230824e-16],
       [-1.44328993e-15, -6.66133815e-16, -6.10622664e-16],
       [-1.44328993e-15, -3.88578059e-16, -5.55111512e-16]])

Lo cual se puede verificar también así:

In [14]:
np.isclose(F, R@U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
np.isclose(F, V@R)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Verificación de propiedades

Recordemos que el tensor derecho de Cauchy-Green $\boldsymbol{C}$ se puede escribir como $\boldsymbol{C}=\boldsymbol{F}^T \boldsymbol{F} = \boldsymbol{U}^T \boldsymbol{U} = \boldsymbol{U}\boldsymbol{U}$:

In [16]:
np.all(np.isclose(F.T@F, U@U))

True

y que que el tensor izquierdo de Cauchy-Green $\boldsymbol{B}$ se puede escribir como $\boldsymbol{B} = \boldsymbol{F} \boldsymbol{F}^T = \boldsymbol{V} \boldsymbol{V}^T = \boldsymbol{V} \boldsymbol{V}$:

In [17]:
np.all(np.isclose(F@F.T, V@V))

True

## Cálculo de la descomposición polar $\boldsymbol{F}  = \boldsymbol{R} \boldsymbol{U}$

Se calcula el tensor derecho de Cauchy-Green $\boldsymbol{C}$ se puede escribir como $\boldsymbol{C} = \boldsymbol{F}^T \boldsymbol{F}$:

In [18]:
C = F.T @ F
C

array([[1.87442597, 0.61234485, 0.78210663],
       [0.61234485, 0.30956629, 0.28801157],
       [0.78210663, 0.28801157, 0.41484141]])

Observe que mediante el [teorema de la descomposición espectral](https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix), podemos volver a obtener la matriz $\boldsymbol{C}$ como:

In [19]:
valp, vecp = eigh(C)
vecp @ np.diag(valp) @ vecp.T

array([[1.87442597, 0.61234485, 0.78210663],
       [0.61234485, 0.30956629, 0.28801157],
       [0.78210663, 0.28801157, 0.41484141]])

Observe que la matriz $\boldsymbol{U}$ se puede obtener como:

In [20]:
np.all(np.isclose(U, vecp @ np.diag(np.sqrt(valp)) @ vecp.T))

True

Finalmente $\boldsymbol{R} = \boldsymbol{F} \boldsymbol{U}^{-1}$

In [21]:
np.all(np.isclose(R, F @ inv(U)))

True

## Cálculo de la descomposición polar $\boldsymbol{F}  = \boldsymbol{V} \boldsymbol{R}$

Se calcula el tensor izquierdo de Cauchy-Green $\boldsymbol{B}$ se puede escribir como $\boldsymbol{B} = \boldsymbol{F} \boldsymbol{F}^T$:

In [22]:
B = F @ F.T
B

array([[0.40457862, 0.54879539, 0.57494034],
       [0.54879539, 1.10353844, 1.02127458],
       [0.57494034, 1.02127458, 1.09071661]])

Observe que mediante el [teorema de la descomposición espectral](https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix), podemos volver a obtener la matriz $\boldsymbol{B}$ como:

In [23]:
valp, vecp = eigh(B)
vecp @ np.diag(valp) @ vecp.T

array([[0.40457862, 0.54879539, 0.57494034],
       [0.54879539, 1.10353844, 1.02127458],
       [0.57494034, 1.02127458, 1.09071661]])

Observe que la matriz $\boldsymbol{V}$ se puede obtener como:

In [24]:
np.all(np.isclose(V, vecp @ np.diag(np.sqrt(valp)) @ vecp.T))

True

Finalmente $\boldsymbol{R} = \boldsymbol{V}^{-1}\boldsymbol{F}$

In [25]:
np.all(np.isclose(R, inv(V) @ F))

True

## Calculando la descomposición polar con la descomposición en valores singulares

In [26]:
WW, S, VVH = svd(F)
VV = VVH.conj().T

In [27]:
RR = WW @ VVH
UU = VV @ np.diag(S) @ VVH

In [28]:
np.all(np.isclose(R, RR))

True

In [29]:
np.all(np.isclose(U, UU))

True