# La descomposición polar

In [1]:
import numpy as np
from scipy.linalg import polar

Primero que todo se genera al azar una matriz $\boldsymbol{F}$:

In [2]:
F = np.random.rand(3,3)
F

array([[0.14327529, 0.4234147 , 0.01029867],
       [0.32803259, 0.86791689, 0.9738616 ],
       [0.00593829, 0.9502803 , 0.96165326]])

La descomposición polar la matriz $\boldsymbol{F}$ se puede descomponer así:
\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{v}\boldsymbol{R}
\end{equation*}
donde $\boldsymbol{R}$ es una matriz ortogonal y $\boldsymbol{U}$ y $\boldsymbol{v}$ son matrices simétricas.

La función `scipy.linalg.polar` se puede utilizar para generar la descomposición polar:

In [3]:
R1, U = polar(F, 'right')
R2, v = polar(F, 'left')

Observe que las matrices $\boldsymbol{R}_1$ y $\boldsymbol{R}_2$ son iguales:

In [4]:
R1 - R2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Por lo tanto:

In [5]:
R = R1

Observemos también que $\boldsymbol{R}$ es una matriz ortogonal, es decir, satisface $\boldsymbol{R}^T\boldsymbol{R} = \boldsymbol{I}$:
    

In [6]:
R.T@R

array([[ 1.00000000e+00, -5.40355238e-16,  6.69791160e-17],
       [-5.40355238e-16,  1.00000000e+00, -3.47512123e-16],
       [ 6.69791160e-17, -3.47512123e-16,  1.00000000e+00]])

y que $\boldsymbol{R}$ es una *matriz ortogonal propia*, es decir, su determinante $\det(\boldsymbol{R}) = 1$:

In [7]:
np.linalg.det(R)

-0.9999999999999996

Tanto la matriz $\boldsymbol{U}$ como la matriz $\boldsymbol{v}$ son simétricas:

In [8]:
U

array([[0.27941995, 0.18069487, 0.13206934],
       [0.18069487, 1.08221276, 0.79483161],
       [0.13206934, 0.79483161, 1.10638595]])

In [9]:
v

array([[0.35956861, 0.19919065, 0.17591867],
       [0.19919065, 1.04775513, 0.81964859],
       [0.17591867, 0.81964859, 1.06069492]])

Verifiquemos ahora que:
\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{v}\boldsymbol{R}
\end{equation*}

In [10]:
F - R@U

array([[5.55111512e-17, 3.33066907e-16, 4.77048956e-16],
       [1.11022302e-16, 9.99200722e-16, 8.88178420e-16],
       [1.23165367e-16, 5.55111512e-16, 9.99200722e-16]])

In [11]:
F - v@R

array([[1.66533454e-16, 5.55111512e-16, 5.34294831e-16],
       [5.55111512e-16, 1.11022302e-15, 5.55111512e-16],
       [4.90926744e-16, 9.99200722e-16, 5.55111512e-16]])

Lo cual se puede verificar también así:

In [12]:
np.isclose(F, R@U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
np.isclose(F, v@R)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])