# La descomposición polar

In [1]:
import numpy as np
from scipy.linalg import polar

Primero que todo se genera al azar una matriz $\boldsymbol{F}$:

In [2]:
F = np.random.rand(3,3)
F

array([[0.33688925, 0.44231762, 0.7823989 ],
       [0.14460503, 0.40705974, 0.1338871 ],
       [0.41072114, 0.66087382, 0.20379584]])

La descomposición polar la matriz $\boldsymbol{F}$ se puede descomponer así:
\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{v}\boldsymbol{R}
\end{equation*}
donde $\boldsymbol{R}$ es una matriz ortogonal y $\boldsymbol{U}$ y $\boldsymbol{v}$ son matrices simétricas.

La función `scipy.linalg.polar` se puede utilizar para generar la descomposición polar:

In [3]:
R1, U = polar(F, 'right')
R2, v = polar(F, 'left')

Observe que las matrices $\boldsymbol{R}_1$ y $\boldsymbol{R}_2$ son iguales:

In [4]:
R1 - R2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Por lo tanto:

In [5]:
R = R1

Observemos también que $\boldsymbol{R}$ es una matriz ortogonal, es decir, satisface $\boldsymbol{R}^T\boldsymbol{R} = \boldsymbol{I}$:
    

In [6]:
R.T@R

array([[1.00000000e+00, 4.42174375e-17, 2.00984080e-16],
       [4.42174375e-17, 1.00000000e+00, 5.53672299e-16],
       [2.00984080e-16, 5.53672299e-16, 1.00000000e+00]])

Tanto la matriz $\boldsymbol{U}$ como la matriz $\boldsymbol{v}$ son simétricas:

In [7]:
U

array([[0.3121939 , 0.38273823, 0.24319386],
       [0.38273823, 0.74923994, 0.30041252],
       [0.24319386, 0.30041252, 0.72264487]])

In [8]:
v

array([[0.87322285, 0.19898396, 0.34521662],
       [0.19898396, 0.25623895, 0.31508886],
       [0.34521662, 0.31508886, 0.65461691]])

Verifiquemos ahora que:
\begin{equation*}
\boldsymbol{F} = \boldsymbol{R}\boldsymbol{U}= \boldsymbol{v}\boldsymbol{R}
\end{equation*}

In [9]:
F - R@U

array([[-4.99600361e-16, -9.99200722e-16, -1.22124533e-15],
       [-1.38777878e-16, -3.88578059e-16, -3.05311332e-16],
       [-3.88578059e-16, -6.66133815e-16, -5.55111512e-16]])

In [10]:
F - v@R

array([[-4.44089210e-16, -9.43689571e-16, -9.99200722e-16],
       [-1.11022302e-16, -1.66533454e-16, -4.99600361e-16],
       [-4.44089210e-16, -4.44089210e-16, -7.77156117e-16]])

Lo cual se puede escribir también así:

In [11]:
np.isclose(F, R@U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
np.isclose(F, v@R)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])